### ISSUE TITLE
Config wrong session history path

### ISSUE THREAD

**Issue by Xeratec** [wandb/client#1087]
### Versions
* Weights and Biases version: 0.9.0
* Python version: 3.7.7
* Operating System: Windows 10 Home
* Jupyter Lab:
jupyter-client: 6.1.3
jupyter-console: 6.1.0
jupyter-core: 4.6.3
jupiter: 1.0.0
jupyterlab-server: 1.1.4
jupyterlab: 1.2.6

### Description
I am working with Jupyter Lab. I enabled code saving in my personal account and it does upload the code successfully to the _code_ folder. The problem is that the path in the _config.yaml_ has a backslash instead of a forward slash.
```yaml
wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.7
    session_history: code\_session_history.ipynb
test:
  desc: null
  value: true
```
I am not able to change the path as it gets reset as soon as I rerun the commands below. Because of this error, I get a _No such file!_ error when clicking on the code icon inside the run on www.app.wandb.ai.

### What I Did

```py
import wandb

defaults=dict(
    test = True,
)

wandb.init(project="test", config=defaults)

for i in range(10):
    sleep(0.1)
    print(i)
    wandb.log({"epoch": i/10})
```
