### ISSUE TITLE
Sweeps grid search repeats same run config indefinitely when calling wandb.config.update

### ISSUE THREAD

**Issue by alexmirrington** [wandb/client#1379]
**Known Affected Version(s):**

`0.10.7`

**Details:**
Running a grid search repeats runs with the same config indefinitely. Here is the exact config used:

```
program: code/algorithm/main.py
method: grid
project: "non-negative-matrix-factorisation"
name: "noise-salt-and-pepper"
description: "Grid search over multiple models with salt-and-peppered inputs."
parameters:
  seed:
    values: [0, 1, 2, 3, 4]
  model:
    values: ["standard", "l21"]
  noise-p:
    values: [0.1, 0.2, 0.4]
  noise-r:
    values: [0, 0.5, 1]
  dataset:
    values: ["orl", "yaleb"]
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--wandb"
  - "--noise"
  - "salt_and_pepper"
  - ${args}
```

Since I used enums for the dataset fields in `argparse`, I was told I should set `allow_val_change=True` in `config.update`, since the sweep was receiving the string `orl` but `config.update` was receiving `Dataset.ORL` as a value instead. My code then called `wandb.config.update(config, allow_val_change=True)` after the regular `wandb.init(...)`, which is ignored by sweeps, however the sweep then checks if a run existed with `config.dataset == "orl"` when determining the next run to use. Serialising and deserialising enums before passing to `wandb.config.update` solved the issue, however more enum support would be great.
