### ISSUE TITLE
why does wandb.restore() need a wandb.init()

### ISSUE THREAD

**Issue by kouroshHakha** [wandb/client#1403]
Hi, suppose I want to just download a pre-trained model for inference purposes without creating a new run via a separate script. Why do I have to create a `wandb.init()` to avoid the following error?

`wandb.errors.error.Error: You must call wandb.init() before wandb.restore()`

**Comment by cvphelps** [comment]
Hi there, it normally shouldn't require wandb.init(), thanks for reporting this. Could you share a code snippet or more info so we can repro?

**Comment by lukas** [comment]
The command line wandb restore is an easy way to get a pretrained model but your point is valid we should not require wandb.init() before wandb.restore(). @vanpelt actually has a todo from three months ago to fix this.

**Comment by vanpelt** [comment]
I have a fix for this in: https://github.com/wandb/client/pull/1413

**Comment by raubitsj** [comment]
This was fixed in 0.10.9

**Comment by kouroshHakha** [comment]
I tested this, and it seems that
```
file = wandb.restor('foo.yaml', run_path=<wandb_run_path>)
content = read_yaml(file)
```
returns the correct content only if I still do a `wandb.init(project='fake_project')` before all of this. I can provide more info if you need to an example to debug.

**Comment by vanpelt** [comment]
Hey @kouroshHakha an example / more info would be helpful.  Specifically what content does it return that isn't "correct"?

**Comment by kouroshHakha** [comment]
It's kinda hard to re-create the setup I have but I'll try to explain. The project that I want to grab the model_config yaml file from has a lot of runs in it. Each have their own `model_config.yaml` that will be used to setup the architecture upon loading. Specifically I'm trying to grab the yaml file for `blooming-lake-99` in [this screen shot](https://ibb.co/QDWNMwx).
However when I passed the unique id of that run in format of `$UserName/$Project/$Runid` it returned some other model_config which I haven't really been able to trace back to other runs. (I suspect that it grabs it from one of the other runs, but because I have so many, I wasn't able to check each individual one). 

The returned content is something like this: 
```
model_config:
  activation: leaky_relu
  bnorm: false
  input_dim: 8
  nh_layer: 4
  nhidden: 500
  nz_dim: 16
  optimize_out: true
  output_act: tanh
  skip_conn: true
```

whereas it should be something like this (according to the web interface):
```
model_config:
  activation: tanh
  bnorm: false
  drop_out: 0.0
  input_dim: 8
  nh_layer: 5
  nhidden: 500
  nz_dim: 16
  optimize_out: true
  output_act: tanh
  skip_conn: false
  use_huber: true
  use_resnet: false
```

and when I do `wandb.init` before `wandb.restore()` it returns the correct yaml.
