### ISSUE TITLE
Sweep configurations

### ISSUE THREAD

**Issue by sheffier** [wandb/client#1420]
Hi I have two questions regarding sweeps:

**1. Is it possible to re-configure a sweep?** 

Consider the following simple example:

- I have a single hyperparameter - `learning_rate`.
- I create the following sweep configuration YAML file (named `wandb_conf.yaml`):
```
program: main.py
method: grid
metric:
  name: val_acc
  goal: maximize
parameters:
  learning_rate:
    distribution: categorical
    values: [1e-5, 1e-4, 1e-3, 1e-2]
```
- I create a new sweep using the following command: `wandb sweep wandb_conf.yaml`
- New sweep is created with ID `SWEEP_EXAMPLE_ID`
- I start the sweep by running `wandb agent SWEEP_EXAMPLE_ID`
- After the agent runs several experiments, it's obvious that setting `learning_rate` to `1e-2` is bad for the model

What I would like to do is:
- Pause the sweep.
- Update the sweep's configuration by removing the value `1e-2` from the list of values of the `learning_rate` parameter:
```
parameters:
  learning_rate:
    distribution: categorical
    values: [1e-5, 1e-4, 1e-3]
```
- Continue sweep

**2. Is it possible to assign per-agent command line parameters?**
Let's say that my program accepts the command line argument `--gpus` which sets the number of GPUs it uses.
If I set this argument in the sweep's YAML file, e.g.:
```
command:
      - "--gpus"
      - "4"
```

then, each agent that starts, will start an experiment using 4 GPUs.

This behavior is too strict. Let's say I have two servers. Server A with 4 GPUs and server B with 8 GPUs.
What I would like to be able to do is:

- On server A: `wandb agent SWEEP_ID --gpus 4
- On server B: `wandb agent SWEEP_ID --gpus 8
