### ISSUE TITLE
WandB client error when tuple used in sweeps config

### ISSUE THREAD

**Issue by nsfabina** [wandb/client#1493]
**Python version**: 3.7
**Wandb versions tested**: 0.10.6 to 0.10.10
**OS**: Linux

**Summary**:  Wandb sweep agents will run once and then error out on all subsequent runs. The observed error is the anaconda 400 / graphql 500 error that I've seen here frequently, but the nested error is the common numpy error that goes something like "boolean from array makes no sense, use np.all or np.any". It was pretty uninformative, but I think I've tracked down the issue.

**Use case**:  I have a couple hyperparameters that are categorical but dependent on one another. Example:  param A could be values X, Y, Z and param B could be values L, J, K, but only certain combos make sense, e.g., (X, L), (X, J), (Y, J), (Z, K). Rather having those listed as separate params and wandb passing combos that don't make sense, I configured those params to be tuples. Note that the current docs say categorical values can have distribution defined by "values: [(value), (value)...]", but does not suggest that "value" cannot be a tuple.

**Sample configuration dictionary**:
```
        "parameters": {
            ...
            "linked_hypers": {"distribution": "categorical", "values": [(0, 0), (8, 8), (8, 16), (16, 8), (16, 16)]},
            ...
        },
```

**Solution**: I ended up encoding these tuples as strs in the config, e.g., "8,8", then splitting and casting to the actual parameter values in my code. The errors stopped. However, it'd be nice to either have support for tuples, have informative error messages when this happens, or have more info in the docs, but I'm guessing the quickest/easiest solution on your end is just to have more rigorous input checks when sweep configs are submitted.

(Apologies for not grabbing the actual stacktrace)

Thanks!

**Comment by cvphelps** [comment]
Hi there, thanks for reporting this issue! It's a good idea, and we'll add to our backlog

**Comment by nsfabina** [comment]
No problem, I'm great at breaking things. Thanks and have a good day.

**Comment by farizrahman4u** [comment]
Got a script to reproduce? Following works for me:

```python
import wandb

sweep_config = {
  "name": "My Sweep",
  "method": "grid",
  "parameters": {
        "param1": {
            "values": [1, 2, 3]
        },
        "param2":{
            "distribution": "categorical",
            "values": [(0, 0), (8, 8), (8, 16), (16, 8), (16, 16)]
        }
    }
}

sweep_id = wandb.sweep(sweep_config)

def train():
    run = wandb.init()
    print(run.config.param2)
    run.finish()

sweep_id = wandb.sweep(sweep_config)
agent = wandb.agent(sweep_id=sweep_id, function=train)
agent.run()

```

**Comment by nsfabina** [comment]
Hey, sorry, I don't have a script to reproduce. This is all embedded within a more complex set of scripts and it'd take a little longer to pull it all out. I can confirm that your script works for me locally and I will make a note to revisit this when time permits and see if I can pull out the relevant lines of code to reproduce. 

Until then, there are actually a limited set of differences between your toy example and my code. My config also defines the search/stopping parameters and I'm modifying the wandb run name, but the big difference is that I'm running the agent using `wanbd agent <sweep info>` from the command line, and the python command is specified in the sweep config. I strongly suspect this is the key difference because the error was occurring before my code was reached. Example:

```
    sweep_config = {
        ...
        "command": [
            "python",
            "-c",
            "import our_package; our_package.train_model()",
        ],
       ...
    }
```

Then, within `our_package`:
```
def train_model():
    import ipdb; ipdb.set_trace()   # Added this line to debug what was happening with the client error
    # Train model
```

Note that I added the `ipdb` import to try and determine what was happening and the line would be reached on the first run for the agent, but would not be reached on any subsequent run. That is, the error was occurring before the wandb agent could run `train_model`. So, if I was trying to reproduce this, I'd write a config that implemented the sweep via the command line specifically.

I hope that's helpful.

**Comment by acauquil** [comment]
Hi, I'm having the same issue using a `.yaml` file for the sweep. Here is my config : 
```yaml
program: model.py
method: bayes
metric:
  goal: minimize
  name: loss
parameters:
  CONVOLUTIONAL_LAYERS:
    values: [1, 2, 3, 4]
  CONVOLUTIONAL_ACTIVATION:
    values: ["tanh", "softmax", "relu", "sigmoid"]
  FILTERS_CL1:
    values: [10, 25, 50, 75, 100]
  FILTERS_CL2:
    values: [10, 25, 50, 75, 100]
  FILTERS_CL3:
    values: [10, 25, 50, 75, 100]
  FILTERS_CL4:
    values: [10, 25, 50, 75, 100]
  WINDOW_SHAPE_CL1:
    values: [(3, 3), (3, 5), (5, 5), (3, 25), (5, 25), (3, 75), (5, 75)]
  WINDOW_SHAPE_CL2:
    values: [(3, 3), (3, 5), (5, 5), (3, 25), (5, 25), (3, 75), (5, 75)]
  WINDOW_SHAPE_CL3:
    values: [(3, 3), (3, 5), (5, 5), (3, 25), (5, 25), (3, 75), (5, 75)]
  WINDOW_SHAPE_CL4:
    values: [(3, 3), (3, 5), (5, 5), (3, 25), (5, 25), (3, 75), (5, 75)]
  FULLY_CONNECTED_LAYERS:
    values: [1, 2, 3]
  FULLY_CONNECTED_ACTIVATION:
    values: ["tanh", "softmax", "relu", "sigmoid"]
  HIDDEN_UNITS_FCL1:
    values: [200, 500, 1000]
  HIDDEN_UNITS_FCL2:
    values: [200, 500, 1000]
  HIDDEN_UNITS_FCL3:
    values: [200, 500, 1000]
```
Here is an example of parsed values by the agent
```
WINDOW_SHAPE_CL1: 5)
WINDOW_SHAPE_CL2: (3
WINDOW_SHAPE_CL3: 25)
WINDOW_SHAPE_CL4: 75)
```
I tried to escape the comma, same results.
