### ISSUE TITLE
Bayes sweep evaluates same set of parameters multiple times

### ISSUE THREAD

**Issue by michalmisiewicz** [wandb/client#1660]
Given following configuration:
```python
sweep_config = {
    'name': 'my-awesome-sweep',
    'method': 'bayes',
    'metric': {
      'name': 'val_root_mean_squared_error',
      'goal': 'minimize'
    },
    'parameters': {
        'batch_size': {
            'values': [256, 512, 1024, 2048, 4096, 8192]
        },
        'learning_rate': {
            'values': [1e-2, 1e-3, 1e-4, 5e-4, 5e-5, 1e-5]
        },
        'activation': {
            'values': ['relu', 'elu', 'selu']
        }
    }
}
```

Bayes sweep evaluates same set of parameters multiple times:

![image](https://user-images.githubusercontent.com/16355374/103487347-f90ac380-4e04-11eb-81ca-f71f574187fa.png)

Is there any solution to evaluate set of parameters only once ?

**Comment by vanpelt** [comment]
Hey @michalmisiewicz can you share a link to the sweep?

**Comment by michalmisiewicz** [comment]
Hey @vanpelt, sure. [sweep url](https://wandb.ai/mm_magisterka/multimodal/sweeps/yjrws03e?workspace=user-mm_magisterka)

**Comment by sergeyk** [comment]
Facing this issue too @vanpelt.

See top two rows here:
<img width="1920" alt="CleanShot 2021-02-21 at 18 26 47@2x" src="https://user-images.githubusercontent.com/4881/108649791-e3b02e00-7472-11eb-8e8b-8450a625dd59.png">

https://wandb.ai/sergeyk/fsdl-text-recognizer-2021-training/sweeps/twpvro2d/table?workspace=user-sergeyk

```
command:
  - ${env}
  - /home/sergeyk/miniconda3/envs/fsdl-text-recognizer-2021/bin/python
  - ${program}
  - "--wandb"
  - "--reduce_lr_on_plateau"
  - ${args}
program: training/run_experiment.py
method: bayes
metric:
  goal: minimize
  name: val_cer
early_terminate:
  type: hyperband
  min_iter: 20
parameters:
  early_conv_dim:
    values: [32, 64]
  late_conv_dim:
    values: [64, 128]
  window_width:
    values: [18, 24, 30]
  window_stride:
    values: [4, 8]
  fc_dim:
    values: [512, 1024, 2048]
  max_epochs:
    value: 1000
  num_workers:
    value: 20
  gpus:
    value: -1
  data_class:
    value: IAMLines
  model_class:
    values: [LineCNN, LineCNNLSTM]
  loss:
    value: ctc
  precision:
    value: 16
```
