### ISSUE TITLE
Error while calling W&B API: Sweep user not valid (<Response [400]>)

### ISSUE THREAD

**Issue by nialloh23** [wandb/client#1883]
**Description**
I'm trying to setup my first sweep run. When I run `wandb sweep training/sweep.yaml` I get prompted to enter my API key (doesn't seem to pick up from my machine). It then tries to create a sweep but throws an error that the sweep user is not valid. My API key works for my normal wandb logging.

**Step 1: I'm prompted to enter my API Key**
```
wandb sweep training/sweep.yaml
wandb: Login to W&B to use the sweep feature
wandb: You can find your API key in your browser here: https://wandb.ai/authorize
wandb: Paste an API key from your profile and hit enter: 
```
**Step 2: Get the following error message**
```
wandb: Appending key for api.wandb.ai to your netrc file: /Users/nohara/.netrc
wandb: Creating sweep from: training/sweep.yaml
400 response executing GraphQL.
{"errors":[{"message":"Sweep user not valid","path":["upsertSweep"]}],"data":{"upsertSweep":null}}
wandb: ERROR Error while calling W&B API: Sweep user not valid (<Response [400]>)
```

## My Sweep File  
```
program: training/run_sweep.py
method: grid
project: size_embeds
entity: rtr-team1
metric:
  name: loss
  goal: minimize
parameters:
  dataset:
    value: SizeEmbedDataset
  model:
    value: CandidateTrainer
  network:
    value: candidate_network_mf
  network_args.embedding_size:
    values: [16, 32, 64, 128]
  train_args.batch_size:
    values: [1024, 2048, 4098, 8024]
  train_args.num_epochs:
    values: [4, 7, 10, 15, 20]
  train_args.learning_rate:
    values: [0.001, 0.005, 0.01, 0.05, 0.1]
```

**Environment**
- OS: MAC OS Big Sur
- Environment: PyCharm
- Python Version: 3.8
