### ISSUE TITLE
[CLI] wandb init from yaml file fails

### ISSUE THREAD

**Issue by fwilliams** [wandb/client#1913]
**Description**
When I run
```python
wandb.init(..., config='/path/to/config.yaml')
```
I get an error
```
TypeError: string indices must be integers
```
at
`sdk/lib/sdk/lib/config_util.py:114`

I believe the line `data[k] = v["value"]` should be `data[k] = v`.

**Wandb features**

```python
wandb.init(config='someyamlfile.yaml`)
```

**How to reproduce**
Create `test.yaml` as:
```yaml
foo: "bar"
baz: "bat"
```
Run:
```
import wandb

wandb.init(config='./test.yaml')
```

**Environment**
- OS: Ubuntu 20.04
- Environment: Conda
- Python Version: Python 3.7.9
- Wandb version: 0.10.20

**Comment by vanpelt** [comment]
Hey @fwilliams when using our config loading logic you must format your config file as follows:

```
foo:
  value: "bar"
  desc: "This is what this parameter is for"
baz:
  value: "bat"
  desc: "This is another description"
```

I'm going to keep this ticket open as we should have a much better error message here / potentially support the none value / desc approach to config in a future release.

**Comment by akanakia** [comment]
Has there been an update on this? It would be awesome if wandb could support configs of the format posted by the OP by including the config parsing logic where something like:

```yaml
foo: "bar"
baz: "bat"
```

could be automatically interpreted to:
```yaml
foo:
  value: "bar"
  desc: none
baz:
  value: "bat"
  desc: none
```

The OP yaml format for training configs is very common and much easier to write than conforming to the wandb format, which is too verbose.
