### ISSUE TITLE
Sweep early stopping hyperband not work[CLI] 

### ISSUE THREAD

**Issue by hainanxzg** [wandb/client#1975]
wandb --version && python --version && uname

- Weights and Biases version: 0.10.20
- Python version: 3.6.8
- Operating System: Ubuntu 18.04 LTS

I train and test my network 10 times in a run and log `test_acc_avg` at every end of training. I set `test_acc_avg` as sweep metric and want to stop early when this run produce low `test_acc_avg`. But it seems hyperband do nothing that every run still train 10 times.

Can you help me?

```yaml
program: train.py
method: bayes
metric:
  name: test_acc_avg
  goal: maximize
early_terminate:
  type: hyperband
  eta: 2
  max_iter: 10
  s: 3
```

The hyperparameter space contains 3600 combinations and the sweep have ran 11 runs now.
