### ISSUE TITLE
[Feature] support nested parameters in .yaml config files 

### ISSUE THREAD

**Issue by willleeney** [wandb/client#2005]
I use pytorch-lightning with the wandb_logger and I am trying to get the sweep working with multiple config files. I don't use the wandb.config for my config location, instead it is stored in the model. The structure of the sweep_config.yaml is very different to my default_config files. What I would really like to be able to do is specify the full name of the parameter as it would appear in my config files, in the sweep_config.yaml file?

so rather than do this: 

**sweep_config.yaml**
```
program: main.py
method: random
metric:
  name: total_loss
  goal: minimize
parameters:
  recon:
    values: [ 1., 0.1, 0.01 ] 
```
**default_config.yaml**

```
model:
  gamma:
    recon: 1.
    cluster: 0.1
```
 
**code**
```
to_merge = OmegaConf.create(wandb.config._as_dict())
config.model.gamma.recon = to_merge.recon
... etc for every parameter in sweep
```

instead I want to be able to do this:

**sweep_config.yaml**
```
program: main.py
method: random
metric:
  name: total_loss
  goal: minimize
parameters:
  model.gamma.recon:
    values: [ 1., 0.1, 0.01 ] 
```
**default_config.yaml**

```
model:
  gamma:
    recon: 1.
...
```
**code**
```
from OmegaConf import open_dict

to_merge = OmegaConf.create(wandb.config._as_dict())
with open_dict(config):
    config = OmegaConf.merge(config, to_merge)

```

I have tried doing this myself using nested parameters in the sweep_config.yaml and creating the config from the command line using `OmegaConf.from_cli()`. 

Any help appreciated, thanks.

**Comment by Linux-cpp-lisp** [comment]
Seconding this feature request — some nested model structures map very naturally to nested configurations, and flattening those configurations requires significant code bloat inside the model creation.

Being able to do sweeps for nested parameters without either having to add (1) all of that config-flattening logic in model building or (2) manually constructing all combinations of nested parameters for the sweep config would be _really_ helpful.

**Comment by bernatGene** [comment]
Also Seconding this feature request. The workaround of re-nesting the parameters flattened by the sweep is very ugly and tedious.

**Comment by armanhar** [comment]
Hey @bernatGene, thanks for writing in. We have a ticket for this feature, I'll bump up its priority and let you know once there are updates

**Comment by RobRomijnders** [comment]
Would also appreciate such feature!

**Comment by nicofirst1** [comment]
I don't get why this was closed, it would be a nice feature to have

**Comment by kenfus** [comment]
Yep, if you define most of your configurations for your project in a single file, you will very probably land at a nested yaml file.

**Comment by pkuderov** [comment]
I think we do exactly what you want in our project, so, probably, someone will find our code useful.

Previously, we ran sweeps with a console wandb api like `wandb sweep ...` and recently we switched to python-only version. We decided to keep supporting both for now:

1. Console: wandb passes sweep parameters as run args  
  `python <your_run_script> <sweep_param1>=<value> <sweep_param2>=<value>`
   
    For this we use following scheme:

```python
TConfig = dict[str, Any]
TConfigOverrideKV = tuple[list, Any]

parser = ... # declare your argparse.ArgumentParser

# sweep params go to unknown_args — list of strings "<param>=<value>"
args, unknown_args = parser.parse_known_args()

# read_config reads yaml config stored in a file with ruamel.yaml
config: TConfig = read_config(args.config_filepath)

# parse sweep params; we discuss parse_arg below
config_overrides: list[TConfigOverrideKV] = list(map(parse_arg, unknown_args))

# apply sweep param values
override_config(config, config_overrides)

# as the result we have a compiled config dict that is ready to be used
```

3. Python api: sweep parameters are passed as dict in `wandb.config` after calling `wandb.init()` for an agent's job. Here's how we handle it:

```python
run = wandb.init()

# as in 1. we first parse each of the dict items. 
# But here each sweep param is a tuple ("path.to.param.key", value)
sweep_overrides = list(map(parse_arg, run.config.items()))

# then as in 1. we just apply parsed overrides to compile resulting config dict
override_config(config, sweep_overrides)
```

<details>
<summary>An example of sweep config that we use (click to expand):</summary>

```yaml
program: run.py

project: temporal_pooling
method: grid
parameters:

  temporal_pooler.:
    value: ablation_utp

  seed.:
    values: [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]

  temporal_poolers..ablation_utp.first_boosting:
    values: [True, False]

  temporal_poolers..ablation_utp.second_boosting:
    values: [True, False]

  temporal_poolers..ablation_utp.untemporal_learning:
    values: [True, False]

  temporal_poolers..ablation_utp.union_learning:
    values: [True, False]

  temporal_poolers..ablation_utp.history_learning:
    values: [True, False]

command:
  - ${env}
  - python
  - ${program}
  - ${args}

    # REQUIRED
  - --config
  - ./configs/policy.yaml
```
</details>

Here's how we parse flatten notation:

```python
# It accepts both a) "<param>=<value>" and b) tuple("path.to.param.key", value) input formats
def parse_arg(arg: Union[str, tuple[str, Any]]) -> TConfigOverrideKV:
    if isinstance(arg, str):
        # raw arg string: "key=value"

        # "key=value" --> ["key", "value"]
        key_path, value = arg.split('=', maxsplit=1)

        # In case a run arg was specified with "--" prefix
        # "--key" --> "key"
        key_path = key_path.removeprefix('--')
    else:
        # tuple ("key", value) from wandb config of the sweep single run
        key_path, value = arg

    # We parse key tokens as they can represent array indices (0, 1, 2, .. etc)
    # We skip empty key tokens (see the post's last spoiler section for an explanation)
    key_path = [
        parse_str(key_token)
        for key_token in key_path.split('.')
        if key_token
    ]
    value = parse_str(value)

    return key_path, value
```

So, each sweep param key is parsed to a list of keys, which we then use to reach the needed level of the nested config to rewrite specified param's value. `override_config` function does the latter part:

```python
def override_config(
        config: TConfig,
        overrides: list[TConfigOverrideKV]
) -> None:
    """Applies the number of overrides to the content of the config dictionary."""
    for key_path, value in overrides:
        c = config
        for key_token in key_path[:-1]:
            c = c[key_token]
        c[key_path[-1]] = value
```

If you want to see, how the code looks like altogether, [here's](https://github.com/AIRI-Institute/him-agent/blob/7677c115412b16f64c859502f9624e660da29f5e/hima/common/run_utils.py#L157) how it looks like in our project.

<details>
<summary>Other helpers that are mentioned in the code above (click to expand):</summary>

```python
TConfig = dict[str, Any]
TConfigOverrideKV = tuple[list, Any]

def read_config(filepath: str) -> TConfig:
    filepath = Path(filepath)
    with filepath.open('r') as config_io:
        return yaml.load(config_io, Loader=yaml.Loader)

def parse_str(s: str) -> Any:
    """Parse string value to the most appropriate type."""

    # noinspection PyShadowingNames
    def boolify(s):
        if s in ['True', 'true']:
            return True
        if s in ['False', 'false']:
            return False
        raise ValueError('Not Boolean Value!')

    # NB: try/except is widely accepted pythonic way to parse things

    # NB: order here is important
    for caster in (boolify, int, float, literal_eval):
        try:
            return caster(s)
        except ValueError:
            pass
    return s
```
</details>


<details>
<summary>If you have noticed that we use double-dotted param names in sweep, here's the [probably not so easy to read] clarification (click to expand)</summary>

Using sweeps we have a little problem with config logging. All parameters provided to a run from a sweep are logged to wandb automatically. At the same time, when we also log our compiled config dictionary, its content is flattened such that each param key is represented as `path.to.nested.dict.key`. Note that we declare params in sweep config the same way. Therefore, each sweep run will have sweep params duplicated in the wandb project table and there's no correct way to distinguish them. Although, wandb somehow does it! Also, only sweep runs will have params duplicated. Simple runs don't have the second entry because they don't have sweep param args.

**Problem**: when you want to filter or group by param in wandb interface, you cannot be sure which of the duplicated entries to select. However you want to group only by the config param — the only entry that is presented in all runs [either sweep or simple] is the entry from our compiled config, not from a sweep itself.

**Solution**: That's why we introduced a trick — we specify sweep param with insignificant additional dots (e.g. `path..to...key.`) to visually distinguish sweep param from the compiled config param. As the result, we need to ignore these dots [or empty path elements introduced by them after split-by-dots] while parsing the key path.
</details>
