### ISSUE TITLE
[Q] Correlation for categorical values in parameter importance panel

### ISSUE THREAD

**Issue by CrohnEngineer** [wandb/client#2126]
Hello,

I'm a newbie in using wandb, so I would like to first thank you for such an amazing tool!  It is really improving the management of my ML projects :)
I have a small question regarding the parameter importance panel of the sweeps.
I've read the [documentation](https://docs.wandb.ai/ref/app/features/panels/parameter-importance) about it, and got the difference between importance and correlation.
Still, I was wondering: let's suppose I have a CNN, and I want to perform a hyperparameter search to find the best architecture for my task. 
Therefore, I am sweeping also on some architectural choices like the layers' activation functions, type of padding, etc.,  with a configuration file like the following:

```
name: my_sweep
metric:
  goal: minimize
  name: val_loss
program: my_train_script.py
method: grid
early_terminate:
  type: hyperband
  s: 2
  eta: 3
  max_iter: 27
parameters:
  activation:
    values: ['ReLU', 'Tanh', 'LeakyReLU']
 pad:
    values: ['zero', 'reflection']
 other_architecture_params:
     values: etc...
project:
  My-project
```

I understand the purpose of the correlation panel when we have a numerical value, like for instance the learning rate of our optimizer, but how should I interpret it when it comes to categorical values like the choice of an activation function, or of one optimizer over another?
A positive high correlation implies that the specific choice of that parameter (i.e. activation = ReLU) correlates with a high value of my metric (i.e., high value of validation loss)?

Thank you in advance for your time :)
