### ISSUE TITLE
Sweeps double-log the command-line arguments as command_line

### ISSUE THREAD

**Issue by drozzy** [wandb/client#2623]
Sweeps logs all arguments again, using lowercase. So if I have a command line argument `batch-size` sweep will log both `batch-size` and `batch_size` (underscore).

![Screenshot from 2021-08-31 20-10-54](https://user-images.githubusercontent.com/140710/131591726-897e975b-76e0-4578-b612-7bafbc51febf.png)

# To reproduce

If I have a script, that uses command line args as follows:

```python
import wandb
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('-b', '--batch-size', type=int, default=8, metavar='N',
                     help='input batch size for training (default: 8)')
args = parser.parse_args()

with wandb.init(config={"lr": 0.1}) as run:
    wandb.config.epochs = 4

    wandb.config.update(args) # adds all of the arguments as config variables
```

Here is my sweep config:
```yaml
project: TEST
program: test.py
method: grid    
parameters:
  batch-size: 
    values: [24, 45]
      
command:
  - ${env}
  - python
  - ${program}
  - ${args}
```

Then initiate a sweep as follows:
```python
wandb sweep test.yaml
```
