### ISSUE TITLE
[Feature] Add distribution type of "range" for grid method

### ISSUE THREAD

**Issue by XiaomoWu** [wandb/client#2665]
Currently, if I want to try out 5 random seeds, then I have to specify in the config.yaml file like this (suppose I'm using grid search):

```yaml
method: grid

seed:
    values: [0,1,2,3,4]
```
However, the key `values` become useless when the number of trials is large. For example, if I want to try every integer random seed from 0 to 1000, it just doesn't make too much sense to write out all the candidates.

Is it possible to add something like
```yaml
seed:
    distribution: range
    min: 0
    max: 1000
    step: 1
```

I apologize if it's already been implemented but I missed it.
Thank you!

**Comment by vanpelt** [comment]
Hey @XiaomoWu you should be able to do this today with:

```
seed:
  distribution: int_uniform
  min: 0
  max: 1000
```

You'll need to change the method to "random" instead of grid but the system should explore all values between 0 and 1000 in that case.  I'll keep this open as we may want to add support to grid search supporting bounded distributions like this.
