### ISSUE TITLE
CLI hangs on sweep validation errors

### ISSUE THREAD

**Issue by raubitsj** [wandb/client#293]
* Weights and Biases version:  0.6.34
* Python version: 3.6.4
* Operating System: Linux

### Description

Create a sweep config with an invalid parameters and try to initialize a sweep.  The client will hang retrying the invalid config.

### What I Did

Example bad sweep exerpt
```
parameters:
  dropout_1:
    min: 0
    #max: 0.4
```

wandb sweep badsweep.yaml
