### ISSUE TITLE
[Q] sweep launches only one run

### ISSUE THREAD

**Issue by yolkandwhite** [wandb/client#3066]
this is my sweep configs.

```
method: bayes
metric:
  goal: minimize
  name: G/latent_cyc
parameters:
  lambda_reg:
    distribution: uniform
    max: 1
    min: 0
  lambda_sty:
    distribution: uniform
    max: 1
    min: 0
  lr:
    distribution: uniform
    max: 0.001
    min: 5e-05
program: main.py
```

why is sweep running only one??

<img width="1544" alt="스크린샷 2021-12-18 오후 3 03 17" src="https://user-images.githubusercontent.com/53941554/146631202-2103a880-30e3-41b0-a1f7-4951056c337e.png">
<img width="833" alt="스크린샷 2021-12-18 오후 3 03 41" src="https://user-images.githubusercontent.com/53941554/146631218-e95de434-4f55-4fd2-8bae-6f5e92314aca.png">
