### ISSUE TITLE
[Q] Sweep only happening over one parameter

### ISSUE THREAD

**Issue by vineetrshenoy** [wandb/client#3273]
I am trying to run a sweep for my experiment my issue is:

**I specify various values over which to sweep; however, the sweep only occurs over the first value**

For example, I am using the following `testsweep.yaml` file, and I would like to sweep over the three values of `shift`

```
program: tools.train_net
method: grid
project: faster_rcnn_R_101_FPN_ft_novel_1
entity: vshenoy
metric:
  goal: minimize
  name: cls_loss
parameters:
  shift:
    values: [0,1,2]
early_terminate:
  type: hyperband
  min_iter: 3
command:
  - ${env}
  - python3
  - -m
  - ${program}
  - "--num-gpus"
  - 2
  - "--config-file"
  - "configs/COCO-detection/faster_rcnn_R_101_FPN_ft_novel_1shot.yaml"
  - "--opts"
  - 'MODEL.WEIGHTS'
  - '/cis/home/vshenoy/FewShotObjectDetection/TFA-with-Mahalanobis/checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_all/model_reset_combine.pth'
```

I run the appropriate sweep command `wandb sweep testsweep.yaml` and the sweep's config file appears correctly in my online account
![Screenshot from 2022-02-22 11-08-56](https://user-images.githubusercontent.com/5201109/155172366-bed5ba81-2160-40dd-bde0-96524143035d.png)

I then run the sweep agent as `wandb agent vshenoy/faster_rcnn_R_101_FPN_ft_novel_1/[sweep_id]` and my training occurs as expected; however, there is no sweep of `shift` values `1` and `2`. When I print `wandb.config` it only shows the first shift value `{'shift': 0}`. The sweep completes only over this value.

What am I doing wrong here? Any pointers would be appreciated! Please let me know if I need to include any more information.
