### ISSUE TITLE
[Q] Running sweeps with groups of parameters

### ISSUE THREAD

**Issue by andreimargeloiu** [wandb/client#3482]
**Context**: I need to compare different combinations of hyper-parameters, where a combination is a group of multiple hyper-parameters.

**Simplified example:** Say I need to compare multiples losses: `loss1`, `loss2`, `loss3`, and for each loss I want to put a known, but different, number of epochs. Thus, my three hyper-parameter combinations are:
1. `loss1` + 100 epochs
2. `loss2` + 200 epochs
3. `loss3` + 300 epochs

**How to create a sweep.yaml to make these two runs in a sweep?**

The following script is wrong, because it will create a cartesian product of 9 run, rather than 3.
```
loss:
    values:
    - loss1
    - loss2
    - loss3

epochs:
    values:
    - 100
    - 200
    - 300
 ```
