### ISSUE TITLE
[CLI]: Importing wandb from a sweep stalls

### ISSUE THREAD

**Issue by cvignac** [wandb/client#3483]
### Describe the bug

Hello,

When running an agent from a sweep, nothing happens: last line printed is 
`wandb: Run sweep agent with: wandb agent ...`

By adding prints to the code, I found that the wandb import stalls. When removing this import, the rest of the code works (with bugs of course, since wandb is not imported).

When running directly the python command displayed in "About to run command:", everything works. 

I tried specifying the environment in the sweep.yaml, but it did not make a difference.

```
wandb sweep ../config/sweep.yaml
wandb agent ...
```

My sweep.yaml is as follows: 

```
program: ../src/regression.py
method: bayes
metric:
  name: Val accuracy
  goal: maximize
parameters:
  alpha:
    min: 0.05
    max: 0.4
command:
  - ${env}
  - /Users/clementvignac/miniconda3/envs/falkon/bin/python3
  - ${program}
  - ${args_no_hyphens}
```

No exception is raised.

### Environment

WandB version: 0.12.12

OS: MacOs

Python version: 3.9.11

Versions of relevant libraries:
hydra-core: 1.1.1
