### ISSUE TITLE
[Q] How to reference previously defined variables in sweep's config.yaml

### ISSUE THREAD

**Issue by Dicer-Zz** [wandb/client#3707]
What do I do if I need the variables to be related to previously defined variables in config.yaml?

For example, I have a variable that is the path to the output folder, and I want this to be related to some method that I defined earlier, like:

```yaml
methods:
  values:
  - SGD
  - Adam
output_dir:
  value: ~/model/${methods}
```

What should I do?
