### ISSUE TITLE
Sweeps documentation: custom command substitution variables

### ISSUE THREAD

**Issue by DuaneNielsen** [wandb/client#865]
`wandb --version && python --version && uname`

* Weights and Biases version:wandb version 0.8.27
* Python version: 3.6
* Operating System: Ubuntu 18.04

### Description

Run a sweep with a custom command

### What I Did

```yaml
program: train_classifier.py 
command:
  - python
  - ${program}
  - "--config"
  - configs/iic/mnist.yaml 
  - "--device" 
  - cuda:0
  - ${args}
method: random
metric: 
  name: test_accuracy
  goal: maximize
parameters:
  data_aug_max_rotate:
    min: 0.05
    max: 0.4
```
Couldn't find documentation for the magic substitutions, specifically the ${args} substitution.  Which seems really important.  In the end I got it by a wild guess.

If it's documented somewhere already, my bad, go ahead and close this out.

Thanks

Duane
